var mongoose = require('mongoose');

var questionSchema = new mongoose.Schema({
    title: String,    
    type: { type: String, default: 'ITEM' },
    error: String,
    dataType: { type: String, default: 'text/xml' },
    qtiXML: String,
    identifier: String,         
    itemType: { type: String, default: 'ITEM' },
    questionType: String,
    questionSubtype: String,
    difficultyLevel: String,
    cognitiveLevel: String,
    concepts: [],
    metadata: String,
    body: String,    
    mediaUrl: String,
    mediaFedoraId: String,
    maxScore: {type: String, default: 1},
    learningGoals: String,
    learningElements: [String],
    reservedForExam: Boolean,
    description: String,
    languageCode: String,
    offerredBy: String,
    owner: String,
    copyRight: String,
    attachments: [String],
    duration: String,
    purpose: String,
    subPurpose: String,
    studyLevel: String,
    learnerLevel: String,
    possibleMarks: String,
    semanticDensity: String,
    knowledgeDimension: String,
    testUsage: String,
    courseId: String,
    status: String,
    isDeleted: Boolean,
    dataMap: {
        Question: String,
        correctAnswer: String,        
        questionFeedback: String,
        Feedback1: String,
        Feedback2: String,        
        Feedback3: String,
        Feedback4: String,
        Answer1:String,
        Answer2:String,
        Answer3:String,
        Answer4:String,
    },
    Status: {
        statusCode: String,
        statusType: String,
        statusMessage: String,
        errorMessages: String
    }
}, { collection: 'questions' });

module.exports = mongoose.model('Questions', questionSchema);
