language: node_js
notifications:
  slack: theselftalk:EHiDWYYgq34Y172TrHTqA16W
node_js:
  - stable
services:
  - docker
before_script:
  - docker-compose -f docker-compose.test.yml up --build -d
  - docker-compose logs mongosetup
  - sh scripts/createSymlinks.sh
install:
  - yarn run install
script:
  - yarn test
after_success:
  - yarn run coverage