version: '2'
services:
  ontology_broker:
    build: 
      context: ./ontology_broker
    env_file:
      - ontology_manager.env
    volumes:
      - ./amqp_utils:/usr/src/app/amqp_utils
      - ./neo4j_utils:/usr/src/app/neo4j_utils
      - ./sro_utils:/usr/src/app/sro_utils
      - ./logs/ontology_broker:/usr/src/app/logs
    links:
      - graphdb
      - mongodb
      - rabbitmq
      - mongosetup
  
  concept_processor:
    build: ./ontology_processors/percp_scope_1.concepts
    env_file:
      - ontology_manager.env
    volumes: 
      - ./amqp_utils:/usr/src/app/amqp_utils
      - ./neo4j_utils:/usr/src/app/neo4j_utils
      - ./sro_utils:/usr/src/app/sro_utils
      - ./logs/concept_processor:/usr/src/app/logs      
    depends_on:
      - ontology_broker
    links:
      - graphdb
      - mongodb
      - rabbitmq

  content_processor:
    build: ./ontology_processors/percp_scope_1.media_content
    env_file:
      - ontology_manager.env
    volumes: 
      - ./amqp_utils:/usr/src/app/amqp_utils
      - ./neo4j_utils:/usr/src/app/neo4j_utils
      - ./sro_utils:/usr/src/app/sro_utils
      - ./logs/concept_processor:/usr/src/app/logs
    depends_on:
      - ontology_broker
    links:
      - graphdb
      - mongodb
      - rabbitmq

  user_processor:
    build: ./ontology_processors/percp_scope_1.user
    env_file:
      - ontology_manager.env
    volumes: 
      - ./amqp_utils:/usr/src/app/amqp_utils
      - ./neo4j_utils:/usr/src/app/neo4j_utils
      - ./sro_utils:/usr/src/app/sro_utils
      - ./logs/concept_processor:/usr/src/app/logs
    depends_on:
      - ontology_broker
    links:
      - graphdb
      - mongodb
      - rabbitmq

  learner_state_processor:
    build: ./ontology_processors/percp_scope_1.learner_state
    env_file:
      - ontology_manager.env
    volumes: 
      - ./amqp_utils:/usr/src/app/amqp_utils
      - ./neo4j_utils:/usr/src/app/neo4j_utils
      - ./sro_utils:/usr/src/app/sro_utils
      - ./logs/concept_processor:/usr/src/app/logs
    depends_on:
      - ontology_broker
    links:
      - graphdb
      - mongodb
      - rabbitmq

  learning_resource_processor:
    build: ./ontology_processors/percp_scope_1.learning_resource
    env_file:
      - ontology_manager.env
    volumes: 
      - ./amqp_utils:/usr/src/app/amqp_utils
      - ./neo4j_utils:/usr/src/app/neo4j_utils
      - ./sro_utils:/usr/src/app/sro_utils
      - ./logs/concept_processor:/usr/src/app/logs
    depends_on:
      - ontology_broker
    links:
      - graphdb
      - mongodb
      - rabbitmq

  node_factory:
    build: ./ontology_processors_neo4j/node_factory
    env_file:
      - ontology_manager.env
    volumes: 
      - ./amqp_utils:/usr/src/app/amqp_utils
      - ./neo4j_utils:/usr/src/app/neo4j_utils
      - ./sro_utils:/usr/src/app/sro_utils
      - ./logs/node_factory:/usr/src/app/logs      
    depends_on:
      - concept_processor
    links:
      - graphdb
      - mongodb
      - rabbitmq

  relation_factory:
    build: ./ontology_processors_neo4j/relation_factory
    env_file:
      - ontology_manager.env
    volumes: 
      - ./amqp_utils:/usr/src/app/amqp_utils
      - ./neo4j_utils:/usr/src/app/neo4j_utils
      - ./sro_utils:/usr/src/app/sro_utils
      - ./logs/relation_factory:/usr/src/app/logs      
    depends_on:
      - concept_processor
    links: 
      - graphdb
      - mongodb
      - rabbitmq
  
  graphdb:
    image: neo4j:latest
    environment:
     - NEO4J_AUTH=neo4j/password
    volumes:
     - ./db/dbms:/data/dbms
    ports:
     - "7474:7474"
     - "7687:7687"
    restart: always

  mongodb:
    image: mongo:latest
    hostname: mongodb
    entrypoint: ["/usr/bin/mongod", "--replSet", "rs"]
    ports:
     - "27017:27017"
     - "28017:28017"
    restart: always
    
  mongosetup:
    image: mongo:latest
    depends_on:
     - mongodb
    volumes:
     - ./scripts:/scripts
     - ./dump:/dump
    entrypoint: ["scripts/mongosetup.sh"]

  rabbitmq:
    image: rabbitmq:management
    ports:
     - "5672:5672"
     - "15672:15672"