version: '2'
services:
  ontology_processors_api:
    build:
      context: ./ontology_processors_api
      dockerfile: Dockerfile.test
    env_file:
      - ontology_manager.test.env
    volumes:
      - ./neo4j_utils:/usr/src/app/neo4j_utils
      - ./sro_utils:/usr/src/app/sro_utils
      - ./logs/ontology_broker:/usr/app/logs
    links:
      - graphdb
      - mongodb
      - rabbitmq
      - mongosetup
    
  graphdb:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./db/dbms:/data/dbms
    ports:
      - "7475:7474"
      - "7688:7687"
    restart: always

  mongodb:
    image: mongo:latest
    hostname: mongodb
    entrypoint: ["/usr/bin/mongod", "--replSet", "rs"]
    ports:
      - "27018:27017"
      - "28018:28017"
    restart: always
      
  mongosetup:
    image: mongo:latest
    depends_on:
      - mongodb
    volumes:
      - ./scripts:/scripts
      - ./dump:/dump
    entrypoint: ["scripts/mongosetup.sh"]

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5673:5672"
      - "15673:15672"