const mongodb = require('mongodb');

const media = [
  {
    _id: new mongodb.ObjectId('58e62ec370528b2f6c86b728'),
    metadata: {
      node_type: 'NODE',
      object_uri: 'info:fedora/learning:1908',
      setType: 'content',
      nodeId: '8mksN0bcr8',
      codeName: '',
      description: '',
      language: '',
      keyword: '',
      offeredBy: '',
      popularity: '',
      rating: '',
      completionResult: '',
      classificationStream: '',
      classificationSubject: '',
      isMandatory: '',
      structure: '',
      aggregationLevel: '',
      currentStatus: '',
      currentVersion: '',
      versionDate: '',
      versionNumber: '',
      versionRole: '',
      versionPerson: '',
      versionStatus: '',
      owner: '',
      copyRight: '',
      cost: '',
      contributors: '',
      annotationRecord: '',
      format: '',
      size: '',
      location: '',
      duration: '',
      purpose: '',
      studyLevel: '',
      learnerLevel: '',
      intendedEndUserRole: '',
      difficultyLevel: '',
      interactivityType: '',
      context: '',
      learningTime: 0,
      semanticDensity: '',
      elementType: '',
      knowledgeDimension: '',
      bloomsTaxonomyLevel: '',
      instructionUsage: '',
      interactivityLevel: '',
      interactivityLocation: '',
      intervention: '',
      interventionRole: '',
      collaboration: '',
      evaluationType: '',
      learningStyle: '',
      placeInContainer: '',
      lessonType: '',
      tutoringMode: '',
      tutorType: '',
      tutorLearnerRatio: '',
      categorizeByLP: '',
      tutorHoursByProfile: '',
      tutorLanguage: '',
      tutorLRTypes: '',
      programTemplate: '',
      programAnswer: '',
      image: '',
      minProficiency: '',
      proficiencyWeightage: '',
      author: '',
      authorImage: '',
      authorProfileURL: '',
      ownerType: '',
      ownerImage: '',
      ownerProfileURL: '',
      offeredByType: '',
      offeredByImage: '',
      offeredByProfileURL: '',
      extendedMaterial: false,
      outcome: '',
      contentSource: '',
      shortDescription: '',
      synopsis: '',
      homeDescription: '',
      weeksDuration: '',
      hoursPerWeek: '',
      hoursOfVideo: '',
      objectives: '',
      projectDescription: '',
      projectImage: '',
      organizationName: '',
      organizationType: '',
      organizationURL: '',
      organizationImage: '',
      price: '',
      tutoringHours: '',
      conceptMapImage: '',
      startDate: '',
      endDate: '',
      timeUnit: '',
      offset: '',
      createdBy: '',
      showOnHomePage: '',
      packagesequenceid: '',
      outcomesequenceid: '',
      posterurl: '',
      height: '',
      width: '',
      packagefolder: '',
      startfile: '',
      title: '',
      mediaurl: '',
      mediatype: '',
      mimetype: '',
      ismain: '',
      contentid: '',
      media: '',
      latype: '',
      usageid: '',
      questionpaperid: '',
      mediaid: '',
      concepts: '',
      packageerror: '',
      identifier: 'info:fedora/learning:1908',
      category: 'main',
      descriptionVerified: false,
      type: ''
    },
    pedagogyId: 'info:fedora/learning:240',
    identifier: 'info:fedora/learning:1908',
    is_deleted: false,
    interceptions: [],
    mediaConcepts: [],
    concepts: [{
      conceptIdentifier: 'info:fedora/learning:7177',
      conceptTitle: 'Properties in Javascript'
    }],
    subtitles: [],
    transcripts: [],
    categories: [
      'main'
    ],
    media: [
      {
        title: 'Deleting Attributes',
        mediaUrl: 'https://niitams.streaming.mediaservices.windows.net/5caf13e1-f039-4c80-97b8-136ffa2f0f6d/video2_5.ism/manifest(format=mpd-time-csf)',
        mimeType: 'application/dash+xml',
        mediaType: 'video',
        mediaId: 'info:fedora/learning:3917',
        isMain: true,
        _id: new mongodb.ObjectId('58e62ec470528b2f6c86ba25')
      }
    ],
    order: 0,
    linkedCourses: [
      'info:fedora/learning:4693',
      'info:fedora/learning:8570'
    ],
    contentType: 'lecture'
  }
];

module.exports = media;
